name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ohcheung/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ohcheung/react-test npm test
 
      - run: docker build -t cheungoihing/multi-client ./client
      - run: docker build -t cheungoihing/multi-nginx ./nginx
      - run: docker build -t cheungoihing/multi-server ./server
      - run: docker build -t cheungoihing/multi-worker ./worker
 
      - run: docker push cheungoihing/multi-client
      - run: docker push cheungoihing/multi-nginx
      - run: docker push cheungoihing/multi-server
      - run: docker push cheungoihing/multi-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multidocker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-181547883832
          region: ap-southeast-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip